packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.4
  "@kyh/prettier-config": ^1.1.4
  "@kyh/tsconfig": ^1.1.4
  "@tanstack/react-query-devtools": ^5.66.11
  "@tanstack/react-query": ^5.66.11
  "@trpc/client": ^11.0.0-rc.772
  "@trpc/tanstack-react-query": ^11.0.0-rc.772
  "@trpc/server": ^11.0.0-rc.772
  "@types/node": ^22.13.5
  "@types/react-dom": ^19.0.4
  "@types/react": ^19.0.10
  "eslint": ^9.21.0
  "next": ^15.2.0
  "prettier": ^3.5.2
  "react-dom": ^19.0.0
  "react": ^19.0.0
  "superjson": "2.2.2"
  "typescript": ^5.8.2
  "zod": ^3.24.2
